# Generated by Django 4.2.1 on 2023-05-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='idImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
    ]
