# Generated by Django 4.2.1 on 2023-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subjects_idimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonslectures',
            options={'verbose_name': 'Связь лекции и уроков'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='courses',
            field=models.ManyToManyField(to='main.courses'),
        ),
        migrations.DeleteModel(
            name='LectureCourses',
        ),
    ]
