# Generated by Django 4.2.1 on 2023-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lessonslectures_options_lecture_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lectures',
            field=models.ManyToManyField(to='main.lecture'),
        ),
    ]
